name: py
on: [push]
jobs:
  builds:
    runs-on: ubuntu-latest
    
    
   steps:
     -name: checkout repe content
      uses: actions/checkout@v2
     -name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8
     -name: execute py script
      run: |
        python hello.py
