name: GitHub Actions to list files
#on: [pull]
jobs:
  list-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
     
